apiVersion: v1
kind: Service
metadata:
  name: finapp-service
spec:
  selector:
    app: finapp
  ports:
    - protocol: TCP
      port: 80  # Exposing the port used by the container
      targetPort: 80
  type: ClusterIP  
