apiVersion: apps/v1
kind: Deployment
metadata:
  name: finapp-deployment
  labels:
    app: finapp
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: finapp
  template:
    metadata:
      labels:
        app: finapp
    spec:
      containers:
        - name: finapp-container
          image: anurag2911/finapp:latest  
          ports:
            - containerPort: 80  
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
            env:
            - name: REACT_APP_AUTH_SERVICE_URL
              value: "http://auth-service:8001"
            - name: REACT_APP_FINANCE_SERVICE_URL
              value: "http://finance-service:8002"
            - name: REACT_APP_NOTIFICATION_SERVICE_URL
              value: "http://notification-service:8003"
            - name: REACT_APP_ANALYTICS_SERVICE_URL
              value: "http://analytics-service:8004"

---

apiVersion: v1
kind: Service
metadata:
  name: finapp-service
spec:
  selector:
    app: finapp
  ports:
    - protocol: TCP
      port: 80  # Exposing the port used by the container
      targetPort: 80
  type: ClusterIP  
