apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finapp-ingress
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /  
    # cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: appsxyzabc.com
      http:
        paths:
          - path: /auth-service/  
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8001
          - path: /finance-service/  
            pathType: Prefix
            backend:
              service:
                name: finance-service
                port:
                  number: 8002
          - path: /analytics-service/  
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 8004
  
