name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using secrets defined in your GitHub repository
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend  # Path to your frontend project (React app)
          push: true
          tags: anurag2911/finapp:latest  # Replace with your DockerHub ID and image name

      # Verify that the image was pushed to Docker Hub
      - name: Docker Hub image info
        run: docker image inspect anurag2911/finapp:latest
